### ISSUE TITLE
[request] BCSTM

### ISSUE THREAD

**Issue by Querdenker9** [libertyernie/LoopingAudioConverter#1]
Many people use this tool to convert MP3 / WAV to BRSTM just to convert it to BCSTM afterwards, to use them in 3DS Themes.
If its possible (it is for sure...), could you please add the possibility to convert to BCSTM directly?
Would be appreciated. Thanks in advance.

**Comment by libertyernie** [comment]
I've added BCSTM support to BrawlLib. Now I just need to put that into LoopingAudioConverter, in two ways:
* for BRSTM->BCSTM or BCSTM->BRSTM, it should ideally do the conversion directly, without re-encoding (much faster and lossless.)
* If the input format is something like WAV or MP3, then it can do the encoding. (Internally it will encode to BRSTM and then convert.)

**Comment by libertyernie** [comment]
I posted a release candidate for version 1.3 with BCSTM support. Try it out and see if it works,
