### ISSUE TITLE
Files converted from .hps loop/end too early

### ISSUE THREAD

**Issue by Singularity3** [libertyernie/LoopingAudioConverter#13]
When I convert .hps files to .brstm, the final few seconds of the file are missing. This happens on both normal and custom looped .hps files. The .hps files in question are made with dsp2hps, and I've tested them to make sure they sound right in .hps.

I've attached two conversions: the first is a file converted from .hps (which was converted from .wav), and the second is the same song converted directly from .wav.

[output.zip](https://github.com/libertyernie/LoopingAudioConverter/files/1273305/output.zip)

**Comment by libertyernie** [comment]
Can you also send me the .hps file?

**Comment by Singularity3** [comment]
[LOOP2.326EO4_Faith_Is_My_Pillar.wav.hps.zip](https://github.com/libertyernie/LoopingAudioConverter/files/1273483/LOOP2.326EO4_Faith_Is_My_Pillar.wav.hps.zip)

**Comment by libertyernie** [comment]
Thanks.
The .hps file has a loop point, but it doesn't seem like it's in the right place. That might be part of the problem.

**Comment by Singularity3** [comment]
That's odd; it sounds like it's in the right place when played through Melee, but maybe it reads the file differently.

**Comment by libertyernie** [comment]
I suppose that could be.
I did try both vgmstream and VGAudio and they did the same thing, but maybe Melee's .hps are different somehow from a normal .hps? I'm not very familiar with it.

**Comment by Singularity3** [comment]
In any case, this program is likely working as intended; I'll probably just have to reconvert from .wav. Thanks!

**Comment by Singularity3** [comment]
As an aside, is there any easy way to set loop-end in the loop.txt file to the end of the song without having to figure out total samples each time?

**Comment by libertyernie** [comment]
I don't think there is now, but that's a good idea.
