### ISSUE TITLE
Error in the saving process

### ISSUE THREAD

**Issue by Ryumarubr** [libertyernie/LoopingAudioConverter#14]
The application is experiencing an error in the process of saving settings.
When I click Save Settings, they are not saved and it looks like the message shown in the image below when the application starts.I use Net Framework 4.5.
https://media.discordapp.net/attachments/281913092009361408/374063406308786177/img.png

Another error, the Ask all files function, creates a noise file if I create a custom track.

I use your application to create bcsmt for 3DS themes.

**Comment by libertyernie** [comment]
That first issue was something I did fix, but I haven't posted a new version since then. I should do that soon.

I'm not sure about the second one. Does it only happen for "ask for all files" and not for the other options?

**Comment by Ryumarubr** [comment]
This error occurs only in the option I reported, noise appears, at the point of tradition, from the custom track (green area) to the repeating loop music track (blue area). The custom track works perfectly until you reach the point that marks the beginning of the repeat loop.

I love your app, and thank you for responding to my support request.

**Comment by libertyernie** [comment]
I forgot to ask - what output format are you using (HPS, etc.)? Also, if you could post a link to your input file, that might help.

**Comment by Ryumarubr** [comment]
I'm using these settings.
https://gbatemp.net/attachments/004-png.104365/
the file is contained in this theme.
https://3dsthem.es/17062

**Comment by libertyernie** [comment]
I don't see that error on my computer. I wonder if it's related to the computer's sound card.

That window, by the way, is from BrawlBox and uses DirectSound for playback. I don't know if that helps or not.

Does the file turn out OK even though you hear noise in that window?

**Comment by Ryumarubr** [comment]
The noise appears in the 3DS, I have 4 3DS and the noise appeared in the 4 3DS.
The image I passed was taken from a tutorial I created, using version 1.4, which I am currently using.
I did not use a version 2 image, because of the problem I had.

**Comment by libertyernie** [comment]
This sounds like it might be an issue with the encoder. The one used in version 2.0 is from VGAudio: https://github.com/Thealexbarney/VGAudio

Any chance you could try using that to convert the bcstm, and see if you have the same problem?

Until then, you should keep using a 1.x version.

**Comment by Ryumarubr** [comment]
I will continue to use version 1.4. Until you can make the new update available, thank you for your attention.

**Comment by Ryumarubr** [comment]
I discovered the problem, apparently if the Ask option is used. In order for the file to be converted without problems in 3ds, the conversion should be done as follows.

Convert from WAV to brstm then use Yata Plus, to convert to bcstm format.
since the LoopingAudioConverter overrides the brstm format settings if you convert to bcstm.

**Comment by libertyernie** [comment]
Good!

Could you post (or send me links to) the working .brstm and .bcstm files? I'd like to try to figure out what the problem is.

**Comment by Ryumarubr** [comment]
The application I used to convert from fornato brstm to Bcstm.
https://github.com/exelix11/YATA-PLUS/releases

My bcstm files.
https://themeplaza.eu/item/3142
https://themeplaza.eu/item/2996

The files in brstm, I do not own at the moment, because I deleted them after converting the files to bcstm.
