### ISSUE TITLE
[Feature Request] Add bcwav support

### ISSUE THREAD

**Issue by CCF100** [libertyernie/LoopingAudioConverter#15]
I'm trying to create a 3ds theme, and I need to convert to a bcwav file.

**Comment by libertyernie** [comment]
Are there any command-line programs that can do this?

If I tried to implement bcwav myself I'd probably mess it up - I'd rather have LoopingAudioConverter use an existing program (like it does for .vgm) or wait for VGAudio to implement .bcwav output support.

**Comment by Algorithmus** [comment]
I have tried to do it with an rstmcpp fork, but it doesn't work so well with multiple channels. It appears to have something to do with how the bcwav channel info is stored. The closest I've come to it is the first channel appears normal, but the second one is offset. Unfortunately, I don't really have much knowledge of audio programming, so maybe someone who does will have an easier time with that.
There's also an Audacity fork that does .bcwav files, but I haven't gotten much out of it.

The pastebin that explains how bcwavs store channel information (at the bottom): https://pastebin.com/1mER2KkD

My attempt at implementing bcwav (also includes a backport of bcstm, feel free to merge/patch): https://gitlab.com/beelzy/rstmcpp/tree/cstm

**Comment by Algorithmus** [comment]
@libertyernie Okay, I fixed it, and you can now properly convert multi channel wav files. You can use it if you'd like. I merged it into master on my fork.

https://gitlab.com/beelzy/rstmcpp/

**Comment by libertyernie** [comment]
Nice! I'll see if I can port the code to C#, and if not I can also just include rstmcpp.exe with the app.

**Comment by libertyernie** [comment]
This ought to work (at least on Windows): https://github.com/libertyernie/LoopingAudioConverter/releases/tag/v2.3.1-rstmcpp

C++/CLI was the easiest way to get something working quickly.

**Comment by Algorithmus** [comment]
rstmcpp should work on Linux at least; that's what I've been developing it on.

**Comment by libertyernie** [comment]
I figured. C++/CLI might not work, though. For the next version I'll probably compile rstmcpp into a separate executable and put it in the tools folder, like I do with vgmstream.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
