### ISSUE TITLE
Error in the Ask option in version 2.1.

### ISSUE THREAD

**Issue by Ryumarubr** [libertyernie/LoopingAudioConverter#16]
The method of creating brstm or bcstm by BrawlLib mode is not working correctly.
The sample rate setting procedure is not working, even if the sample rate is set, the file does not reproduce the created settings. the music plays from start to finish, without performing sample rate settings.

**Comment by libertyernie** [comment]
I think I might know the problem. I'll look into it when I have time.

**Comment by Ryumarubr** [comment]
I believe all other formats are presenting this error in Ask mode.
In any case thanks for your attention.

**Comment by libertyernie** [comment]
I fixed an error with the Ask mode dialog, so you can make looping files now.

I didn't see any problems with the sample rate conversion, though. What input format are you using, and what sample rate are you converting it to?

**Comment by Ryumarubr** [comment]
Eu usei o formato brstm depois eu converti o arquivo para bcstm usando o Yata Plus.

**Comment by libertyernie** [comment]
If you're still having problems with the sample rate in the newest version (2.3rc1), could you open another issue? I'll close this one because the title refers to the Ask problem which is fixed now.
