### ISSUE TITLE
Request: Lossless OGG to OGG?

### ISSUE THREAD

**Issue by iSharingan** [libertyernie/LoopingAudioConverter#2]
Long story short, I have software already that converts to ogg format and I was wondering if there was a way to add the looping metadata without having to re-sample the file (as that never ends well for the sound quality due to the differing sample rates...). I know it stems from SoX, at the moment, as the same issue arises when using the bcstm format to convert from other formats SoX uses and even the ogg I made with my other program. I'm just wondering if the conversion/re-sampling process can be bypassed entirely when using the same file type.

Edit: While this feature would be nice, I found a workaround: avoid ALL file types SoX touches and the sound quality problem vanishes. >.> Would be nice to have looping ogg files, but apparently it's not entirely needed.

**Comment by libertyernie** [comment]
I think an older version of this program did have the ability to add looping metadata, although I don't remember for sure.
Also, what sample rate are you using? I should be able to use the same sample rate throughout the process if I can figure out how.

**Comment by iSharingan** [comment]
I was using 44100 hz (as the song lost too much quality/didn't sound right at anything lower), which was beyond the parameters SoX seems to be capable of reading on an ogg. I've changed a bit in my approach since then and have had no problems when starting by using a file type isn't used to read. Using higher sample rates on non-SoX dependent input file types and outputting through SoX - to, for example, ogg - hasn't caused any sound quality problems as of yet.

In any case, since it's already possible to add loop data via text file, is there a reason we cant just add a manual input for loop data too? Even with the yata+ buggy method of changing a wav into a bcwav, you still had to look up sample numbers in something like audacity. I'm not saying it needs a test player for the audio, but I have been having problems with using a loop.txt file, anyway (the program hangs indefinitely with just the basic file name used, but fully executes when I include the absolute path to the file - however using the absolute path doesn't apply the loop data to the resulting file despite saying it "applied the effects" when none were set in the tool aside from the loop.txt)

Also, as a side note: I may be doing something wrong (though I cant seem to figure out what, unless it's related to the loop.txt problem above), but when sourcing a conversion to ogg from a bcstm that already has loop data, the resulting ogg plays as if it just recorded the loop from the bcstm ( sample 0 -> loopend -> loopstart -> loopend which results in double the length the ogg should be and incorrect loop data stored on it) and, whats more, said result ogg will play through fully once, then only loop the first second ad nauseum (when used in a theme)

**Comment by libertyernie** [comment]
There's probably a bug with loop.txt. Maybe I need to look into that.

I did add an option "Ask for all files" in the "for non-looping files" dropdown; this should pop up a window for each input file (the BRSTM conversion window from BrawlBox) that lets you define a loop point manually.

Unfortunately there's no support for adding loop data to ogg files yet; I would like to add this in the future.

P.S. IIRC, SoX has options you can specify on the command line to control the quality of encoded ogg files, but I didn't add an interface for it in this program (at least not yet.) This is unrelated to the sample rate though.

**Comment by libertyernie** [comment]
I posted a release candidate. Could you test it and see if it does what you want?
