### ISSUE TITLE
I can't use amplitude ratio

### ISSUE THREAD

**Issue by fireluigi12** [libertyernie/LoopingAudioConverter#20]
I would like to set my files to 75% of their original amplitude by setting "Amplify (amplitude ratio)" to 0.75. However, when I enter that number and click somewhere else, it updates to 75 instead.

Since I am German, and the value defaults to 1,000 (with a comma) I thought I might have to use a comma instead of a decimal point. But if I enter 0,75 and try converting, the program locks up at "Applying effects" and I have to close the Progress window with Task Manager. So I assume the tool isn't meant to handle commas there.

Although deamplifying by entering negative values for "Amplify (dB)" does work, I can only set it to a whole number, like -2 or -3, instead of -2.5 like I would like to.

**Comment by libertyernie** [comment]
Nice catch. I'll look into this.

**Comment by libertyernie** [comment]
It should be fixed now. I still need to compile and upload the new version - I'll do that later.

**Comment by libertyernie** [comment]
Uploaded now. Reopen this issue if it doesn't work.
