### ISSUE TITLE
[Feature Request] Tempo and pitch editing

### ISSUE THREAD

**Issue by fireluigi12** [libertyernie/LoopingAudioConverter#21]
First, thank you for fixing the amplitude ratio issue. It works just like it should.

I use my BRSTMs for Mario Kart Wii tracks. The track music in MKWii gets 1 semitone higher and 20% faster when you're in the last lap, so I think it would be nice to have a built-in feature to change the input's pitch and tempo. Switching back and forth between this program and stuff like Audacity is a bit of a hassle.

**Comment by libertyernie** [comment]
That would be a nice feature.

Do you know how to do this effect with SoX? That's what LoopingAudioConverter uses to make these sorts of adjustments.

**Comment by fancymelonub** [comment]
Or you can just use Atlas' [Final Lap Stream Maker](http://wiki.tockdom.com/wiki/Final_Lap_Stream_Maker).

**Comment by libertyernie** [comment]
This seems about right:

sox A13.wav out.wav pitch 100 tempo 1.1

It doesn't give exactly the same effect as Final Lap Stream Maker but based on what I've read, I think it's closer to what the games use.

Next time I update this app I'll add this in.

**Comment by CoroGames1** [comment]
The tempo cannot be increased

**Comment by libertyernie** [comment]
Can't you just use a number over 1.0? Does it not work?

**Comment by CoroGames1** [comment]
> Can't you just use a number over 1.0? Does it not work?

I get an error.

**Comment by libertyernie** [comment]
I can't reproduce the issue. If it only happens on a certain input file, could you post a link to that file?
