### ISSUE TITLE
.bwav files don't seem to work properly

### ISSUE THREAD

**Issue by mariofan12ify** [libertyernie/LoopingAudioConverter#28]
I'm trying to work with Mario Maker 2's .bwav files for the edit tracks and I used the latest build, but still coming up with an error saying they couldn't be read.

**Comment by libertyernie** [comment]
I'm just getting around to addressing issues in this project now (if I can). Do you have a bwav file you could send me? I probably won't be able to do anything about it, but I could try.

**Comment by MDHEXT** [comment]
This issue can be resolved by updating vgmstream.
