### ISSUE TITLE
Missing programs

### ISSUE THREAD

**Issue by myronas34** [libertyernie/LoopingAudioConverter#30]
As soon as I open this, it gives me an error where it says that some programs are missing which causes malfunctions. It says to open some console for more details but how to do that is completely unclear and it happens on two different computers two. What should I do?

![2019-08-16_18-09-21](https://user-images.githubusercontent.com/43584237/63178278-653f2880-c052-11e9-9fbd-324b171a08b6.png)

**Comment by libertyernie** [comment]
This is usually a problem with something in the "tools" folder missing, or with the LoopingAudioConverter.exe.config file not pointing to the write files. You could try running it with the Windows command line (cmd.exe) - I think you can find pointers online about how to do this.

If I update the program I'll probably make this error message better.

**Comment by myronas34** [comment]
I tried looking this up online but it doesn't seem to be possible... Windows is not like Linux were you can run something from the terminal and have console output displayed. PowerShell seems better

If something is missing from that folder, then re-downloading should help right? It doesn't, even if I fallback a few versions. Some really old versions don't report this, but they don't work correctly.

**Comment by libertyernie** [comment]
I posted a new release to fix the problem (it would be nice if I actually *included* the tools folder, I suppose!)

https://github.com/libertyernie/LoopingAudioConverter/releases/tag/v2.3.2

Let me know if this fixes it.
