### ISSUE TITLE
MSU-1 output sample rate

### ISSUE THREAD

**Issue by qwertymodo** [libertyernie/LoopingAudioConverter#32]
MSU-1 files are defined as always being 44.1kHz, so when outputting to MSU-1, the output sample rate should always be set to that.  By default, it's not setting the output sample rate, so it just outputs the samples in their original rate, which leads to songs getting played back either to fast or too slow.

**Comment by libertyernie** [comment]
Thanks for the tip. I made a change that will prompt the user to ask if it's OK to switch to 2-channel 44.1KHz output (even if they've selected mono, or a higher or lower sample rate). Let me know if you want me to do a new build :)

**Comment by libertyernie** [comment]
This should be fixed in version 2.4.
