### ISSUE TITLE
BWAV Support

### ISSUE THREAD

**Issue by DiamC23** [libertyernie/LoopingAudioConverter#35]
I was wondering if it would be possible to add support for converting from/to bwav? (If it's not already planned) It is used in Super Mario Maker 2 and Animal Crossing: New Horizons.

**Comment by MDHEXT** [comment]
This could possibly be resolved by updating whatever version of vgmstream LAC uses.

**Comment by MDHEXT** [comment]
@DiamC23 this issue is resolved by updating vgmstream in the tools folder of loopingaudioconverter.
