### ISSUE TITLE
Ask for loop information broken with multi-channel audio files

### ISSUE THREAD

**Issue by AuraDJ** [libertyernie/LoopingAudioConverter#38]
The option "ask" and "ask for all files" for files with no looping information doesn't work with audio files (I tested with wav), that have more then 2 channels.
I want to convert a 6 channel track for Zelda Botw and while I normally just convert a .ogg with existing loop information, it doesnt bother me. But the official .ogg converter, that Audacity is using, corrupts the 6th channel (apparantly a feature). So I really hope this can be resolved

**Comment by libertyernie** [comment]
This might be fixed in version 2.4
