### ISSUE TITLE
Freezing in process.

### ISSUE THREAD

**Issue by heptominoes** [libertyernie/LoopingAudioConverter#48]
Hello. During the decoding process, it freezes and stops working. Windows 10 user.

**Comment by SysVR** [comment]
Here, if you try to fade out in a time larger than the loop section, it will freeze.

**Comment by resolutezach1** [comment]
well, isn't there a way for it to temporarily remove the fade-out for tracks that don't even have a loop?

**Comment by libertyernie** [comment]
I think this might have been fixed in either 2.5 or 3.0.

**Comment by heptominoes** [comment]
Thank you very much! 3.0 works great. :D
