### ISSUE TITLE
TXTP instructions not being applied

### ISSUE THREAD

**Issue by Tanookirby** [libertyernie/LoopingAudioConverter#56]
I've noticed problems when converting txtp files to other formats. 

First, some rules do not get applied such as padding, trimming, and loop points for txtp files referenced within txtp files.

Second, for files that use **#@volume** to amplify the sound, the program produces output that is around 10 decibels higher than the volume set in the file.

Third, if a **group** command is used (e.g. "group = -L2  #@layer-v") the program won't be able to convert the file at all.

Any way to fix these issues?

**Comment by libertyernie** [comment]
Do you have an example of a txtp file? I imagine it's vgmstream's test.exe that parses these - if that's true, the first thing you could try is replacing test.exe with a newer version.

**Comment by Tanookirby** [comment]
I'll give you examples of all three problems. As for test.exe, I'm fairly certain the foobar installation includes it.
[Examples.zip](https://github.com/libertyernie/LoopingAudioConverter/files/7611273/Examples.zip)
.

**Comment by libertyernie** [comment]
I couldn't get test.exe to read the group command example, but the other two worked fine, and they worked in the newest LoopingAudioConverter as well. I think just updating test.exe fixed it (at least for me) in the new version. So try LoopingAudioConverter 3.0 and see if that works better.

**Comment by Tanookirby** [comment]
This new version seems to hang in the decoding phase.

**Comment by Tanookirby** [comment]
Actually, I managed to make it work, but the bugs are still there.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
