### ISSUE TITLE
Occasional hanging on "Decoding" for wav to brstm conversion, especially when converting in bulk and with multi-channels

### ISSUE THREAD

**Issue by SilverMK6** [libertyernie/LoopingAudioConverter#63]
Not really much else to say, it occasionally will just hang on "Decoding" but closing the program and converting again succeeds, I have a Ryzen 5 5600X, so I doubt it's a cpu issue, these are the exact settings I use

![image](https://user-images.githubusercontent.com/61467007/147293226-8d6d3074-c6e4-49b0-8093-6fc30e5ce4c3.png)

**Comment by libertyernie** [comment]
It's weird that it would hang on decoding a wav, since it doesn't really have to do any decoding at all...

I'm planning on releasing an alternate version that's single threaded eventually, and maybe that'll help.

**Comment by libertyernie** [comment]
Version 3.0 (just posted) goes one file at a time - see if it helps, or at least works differently.

**Comment by SilverMK6** [comment]
late response but yes it does seem to have been fixed, thanks
