### ISSUE TITLE
Ask for loop information doesn't work with more then 2 channels

### ISSUE THREAD

**Issue by AuraDJ** [libertyernie/LoopingAudioConverter#64]
Brstm Import throws a System.ArgumentException when attempting to set a loop point in the program when the music file has more then 2 channels. The file format doesn't matter. It works fine in 2.4

**Comment by libertyernie** [comment]
There's some code to handle this case that was in my copy of the loop dialog but isn't in BrawlLib's. I'll move it to PCM16Audio instead.

**Comment by libertyernie** [comment]
LoopingAudioConverter 3.0 (just posted) should fix this. If 3.0 doesn't work for you, let me know and I can backport the fix to 2.5.

**Comment by AuraDJ** [comment]
It works fine now. Thank you!
