### ISSUE TITLE
FFmpeg is not working at all

### ISSUE THREAD

**Issue by Mode8fx** [libertyernie/LoopingAudioConverter#80]
When I try to convert anything to any format using FFmpeg, I get the error (for example, when attempting to convert to MP3) `Could not encode (MP3Exporter) - ffmpeg quit with exit code 1`.

I've also tried disabling `Skip re-encoding when possible`, but that just makes it hang indefinitely on `Applying effects`. I'm on Windows 11.

**Comment by libertyernie** [comment]
Could you try running LoopingAudioConverter.exe from the Windows command prompt like this, and see if it writes anything to stderr.txt?

    LoopingAudioConverter.exe 2> stderr.txt

**Comment by Mode8fx** [comment]
```
ffmpeg version 2021-12-30-git-12f21849e5-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 13.100 / 57. 13.100
  libavcodec     59. 15.102 / 59. 15.102
  libavformat    59. 10.100 / 59. 10.100
  libavdevice    59.  1.100 / 59.  1.100
  libavfilter     8. 21.100 /  8. 21.100
  libswscale      6.  1.102 /  6.  1.102
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
[wav @ 000001b8e0b74200] invalid start code [91]0B3 in RIFF header
C:\Users\John: Invalid data found when processing input
```
It looks like it's trying to pull something from the C drive and can't properly parse the space in the file path.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
