### ISSUE TITLE
[BRSTM 3.4.1 + LAC 1.3.0.0] Looping while converting 44.1k > 32k

### ISSUE THREAD

**Issue by TonyTheTGR** [libertyernie/LoopingAudioConverter#84]
I've used both the pack-in version of LAC, the currentest build I'm aware of, and BRSTM Convert 3.4.1... which I believe was "this before it was called LAC" - and in both cases, I've been trying to loop songs and convert them to 32000 bitrate simultaneously, and the bitrate conversion causes the program to skip the "define loop" step - it also bypasses loop.txt (I've tried using that too, in both programs/version, after multiplying the 44.1k loop points by .726; the approximate factor difference between the two bitrates).

The thing is, about 5 out of 25 songs looped at 44.1k are working in Remix, no problem - but the rest for some reason seem to crossbleed into each other or other tracks in-game. The bleedover points and other songs are consistent. BrawlCrate plays them just fine/flawlessly, even right off of SD.raw. After seeking help/advice on the Discord, they recommended the 32k conversion when I ran into this issue with the program(s).

Additionally, attempting a 32k conversion on the already-looped 44.1k BRSTM files only output the same 44.1k BRSTM outputs, not converting the bitrates at all.

I'm really just trying to resolve the bleedover issue, ultimately; any insight for how (otherwise?) to do this would be greatly appreciated.

**Comment by libertyernie** [comment]
This is probably a silly question, but what is Remix?

I'd suggest trying to uncheck "skip re-encoding when possible" if you haven't already. In the next version I'm going to replace that with a similar but slightly different feature that will be off by default. I tried using 32000 sample rate and loop.txt together in that upcoming version and it did seem to work correctly.

I guess the other thing you could try is defragmenting the drive that has the files - maybe that'll help?

**Comment by TonyTheTGR** [comment]
PMEX Remix, as I came across it, is a compiled custom build and launcher for SSB Brawl, using a modification fork of Dolphin to load a custom ELF... like the Wii version of Project M. For whatever reason, there's a LAC build included in the files for it, likely for the custom BGM tracks.

The files involved are encoded to a sd.raw file as a virtual ~8GB sim card, and there's an ELF launcher to boot the game using the modified data. Either way, trying a few times to delete, recompile, and readd them eventually tanked my sd.raw so I had to start the process over again, but I am glad to hear about that feature rolling out in case it's necessary to revisit this process!

I do remember unchecking that box in the process, since re-encoding was the whole point of the conversion, and I made sure to empty out the "output" subfolder first, too.

**Comment by libertyernie** [comment]
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.
