### ISSUE TITLE
Document whether it's FLOSS

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [libertyernie/LoopingAudioConverter#91]
The README says:

> **Note:** Each project in this repository has different license terms. See the individual folders for details.

I realize that it would be unwieldy to list all of the various upstream licenses in the README, but it would be useful to at least confirm in the README whether all of the projects are under an FSF/OSI-approved license. I think quite a lot of users care more about whether it's FLOSS than about exactly what the various licenses are for each piece of code.

Thanks.

**Comment by libertyernie** [comment]
The biggest issue is probably the BrawlCrate code, which has always had vague (or no) license terms. But I could (and probably should) make a build without that, where I can clearly specify the license terms of each component. The only things that use BrawlCrate code are the RSTM (etc) encoder/decoder - we also have encoders/decoders for those formats via VGAudio - and the manual loop point selection dialog.

**Comment by Splendide-Imaginarius** [comment]
> The biggest issue is probably the BrawlCrate code, which has always had vague (or no) license terms.

I see, good to know.

> But I could (and probably should) make a build without that, where I can clearly specify the license terms of each component.

That would be excellent, thanks.

**Comment by libertyernie** [comment]
New versions have updated license info in the About.html

Libraries used:

    Name
	    License
    BrawlLib (BrawlCrate)
	    LGPL v3 or later
    OpenTK
	    Mostly MIT, with some code 3-clause BSD
    RunProcessAsTask
	    MIT
    VGAudio
	    MIT
    
    External applications used:
    
    Name
	    License
    ffmpeg
	    GPL v3
    metaflac
	    GPL v2 or later
    qaac
	    Mostly public domain
    VGMPlay
	    Mostly unknown
    vgmstream
	    MIT variant
