### ISSUE TITLE
New sample rate option doesn't upconvert

### ISSUE THREAD

**Issue by VideogameScrapbook** [libertyernie/LoopingAudioConverter#96]
Thank you for this very useful tool! Just wanted to note in case this would be one of the easier things for you to solve:

The **New sample rate (Hz)** option seems to work when downconverting the sample rate (48 kHz to 44.1 kHz), but not when upconverting (32 kHz to 44.1 kHz).

I tried several source file formats including wav.

**Comment by libertyernie** [comment]
I think this has been fixed in 3.2.

**Comment by VideogameScrapbook** [comment]
I confirmed that songs convert properly now when upconverting from 32 to 44.1 kHz.
