### ISSUE TITLE
VCRUNTIME140.dll missing

### ISSUE THREAD

**Issue by martin-braun** [libertyernie/LoopingAudioConverter#99]
On a clean Windows 11 VM:

<img width="414" alt="image" src="https://github.com/user-attachments/assets/c327f1f0-17c3-43ea-97ba-7eb579e471eb">

I needed to install the Microsoft Visual C++ 2015-2019 Redistributable runtime (2019). I would be great to have proper instructions in the README.

**Comment by libertyernie** [comment]
I am thinking about removing this dependency next time I update the app, but I'll add this to the README for now.
